image: gitpod/workspace-mongodb
ports:
  - port: 27017
    onOpen: ignore
tasks:
  - init: |
      npm ci
      mongod --fork --dbpath /data/db
    command: |
      npm i -g pm2
      for file in apps/**/sample.env; do cp $file ${file/sample/}; done;
      npm run start
vscode:
  extensions:
    - dbaeumer.vscode-eslint