tasks:
  - init: |
      npm ci
      npm i -g pm2
    command: |
      for file in apps/**/sample.env; do cp $file ${file/sample/}; done;
      npm run start
vscode:
  extensions:
    - dbaeumer.vscode-eslint