image: gitpod/workspace-mongodb
ports:
  - port: 27017
    onOpen: ignore
  - port: 50000-50200
    onOpen: ignore
    # Set to public for tests to have access across ports
    # Technically, could be configured with `credentials: true` in fetch calls too
    visibility: public
tasks:
  - before: |
      export DEMO_APPS_DOMAIN=$(gp url)
  - init: |
      cp sample.env .env
      npm ci
      mkdir /workspace/log
      mongod --fork --dbpath /data/db --logpath /workspace/log/mongod.log
    command: |
      npm i -g pm2
      for file in apps/**/sample.env; do cp $file ${file/sample/}; done;
      npm run start
vscode:
  extensions:
    - dbaeumer.vscode-eslint
