name: Node.js CI
on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Lint / Build / Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
      fail-fast: false

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start database
        uses: supercharge/mongodb-github-action@d26215f71b2ce60420a2a3776a25893d11a65f85 # v1.9.0

      - name: Install Dependencies
        run: npm ci

      - name: Lint Files
        run: npm run lint

      - name: Run Tests
        run: npm run test-local-or-ci
